style"gtkentry"{
xthickness=1
ythickness=1
GtkWidget::focus-line-width=0
GtkWidget::focus-padding=0
GtkWidget::interior-focus=0
GtkEntry::inner-border={2,2,3,3}
engine"pixmap"{
image{
function=SHADOW
shadow=IN
state=NORMAL
file="../theme/images/shadow.svg"
border={1,1,1,1}
stretch=TRUE}
image{
function=FOCUS
detail="entry"
file="../theme/images/shadow.svg"
border={1,1,1,1}
stretch=TRUE}}}
class"GtkEntry"style"gtkentry"
