# handle this stuff by mist
style"mist"{
xthickness=1
ythickness=1
fg[NORMAL]=@windowtext
fg[PRELIGHT]=@windowtext
fg[SELECTED]=@windowtext
fg[ACTIVE]=@windowtext
fg[INSENSITIVE]=@inactivewindowtext
bg[NORMAL]=@window
bg[PRELIGHT]=@window
bg[SELECTED]=@window
bg[ACTIVE]=@window
bg[INSENSITIVE]=@window
base[NORMAL]=@basebg
base[PRELIGHT]=@basebg
base[ACTIVE]=@hilight
base[SELECTED]=@hilight
base[INSENSITIVE]=@basebg
text[NORMAL]=@basetext
text[PRELIGHT]=@basetext
text[ACTIVE]=@hilighttext
text[SELECTED]=@hilighttext
text[INSENSITIVE]=@inactivewindowtext
GtkWidget::link_color=@url
GtkHTML::link-color=@url
GtkIMHtml::hyperlink-color=@url
GnomeHRef::link-color=@url
GtkWidget::visited-link-color=@visitedurl
GtkHTML::visited-link-color=@visitedurl
GtkIMHtml::hyperlink-visited-color=@visitedurl
engine"mist"{}}
class"GtkAdjustment"style"mist"
#class"GtkViewport"style"mist"
class"GtkAccessible"style"mist"
class"GtkHSV"style"mist"
class"GtkPixmap"style"mist"
class"GtkPreview"style"mist"
class"GtkText"style"mist"
class"GtkTree"style"mist"
class"GtkTreeItem"style"mist"
class"GtkCList"style"mist"
class"GtkCTree"style"mist"
class"GtkCurve"style"mist"
class"GtkGammaCurve"style"mist"
class"GtkPlug"style"mist"
class"GtkSocket"style"mist"
class"GtkDrawingArea"style"mist"
widget_class"*GtkCombo*Cell*"style"mist"