## trough needs to be opaque
##don't change size and co or qgtkstyle breaks
style "gtkscrollbar"="gtkwidget"{
bg[NORMAL]=@scrollbar
bg[PRELIGHT]=@scrollbar
bg[SELECTED]=@scrollbar
bg[ACTIVE]=@scrollbar
bg[INSENSITIVE]=@scrollbar
fg[NORMAL]=@windowtext
fg[PRELIGHT]=@windowtext
fg[SELECTED]=@windowtext
fg[ACTIVE]=@windowtext
fg[INSENSITIVE]=@inactivewindowtext
GtkScrollbar::has_secondary_backward_stepper=0
GtkScrollbar::has_secondary_forward_stepper=0
GtkScrollbar::has_backward_stepper=0
GtkScrollbar::has_forward_stepper=0
engine"pixmap"
{
image
{
function=BOX
orientation=VERTICAL
detail="trough"
file="../theme/images/scrollbar-vertical_trough.svg"
border={1,0,0,0}
stretch=TRUE
}
image
{
function=BOX
orientation=HORIZONTAL
detail="trough"
file="../theme/images/scrollbar-horizontal_trough.svg"
border={0,0,1,0}
stretch=TRUE
}
image
{
function=SLIDER
state=NORMAL
orientation=VERTICAL
file="../theme/images/scrollbar-vertical_slider.svg"
stretch=TRUE
border={2,2,1,1}
overlay_file="../theme/images/scrollbar-vertical_slider_overlay.svg"
overlay_stretch=TRUE
overlay_border={2,2,1,1}
}
image
{
function=SLIDER
state=NORMAL
orientation=HORIZONTAL
file="../theme/images/scrollbar-horizontal_slider.svg"
stretch=TRUE
border={1,1,2,2}
overlay_file="../theme/images/scrollbar-horizontal_slider_overlay.svg"
overlay_stretch=TRUE
overlay_border={1,1,2,2}
}
image
{
function=SLIDER
state=PRELIGHT
orientation=VERTICAL
file="../theme/images/scrollbar-vertical_slider_prelight.svg"
stretch=TRUE
border={2,2,1,1}
overlay_file="../theme/images/scrollbar-vertical_slider_overlay.svg"
overlay_stretch=TRUE
overlay_border={2,2,1,1}
}
image
{
function=SLIDER
state=PRELIGHT
orientation=HORIZONTAL
file="../theme/images/scrollbar-horizontal_slider_prelight.svg"
stretch=TRUE
border={1,1,2,2}
overlay_file="../theme/images/scrollbar-horizontal_slider_overlay.svg"
overlay_stretch=TRUE
overlay_border={1,1,2,2}
}
###thats only here for qgtkstyle
image
{
function=STEPPER
state=NORMAL
file="../theme/images/arrow-bg.svg"
stretch=FALSE
overlay_file="../theme/images/arrow-up_normal.svg"
overlay_stretch=FALSE
arrow_direction=UP
}
image
{
function=STEPPER
state=NORMAL
file="../theme/images/arrow-bg.svg"
stretch=FALSE
overlay_file="../theme/images/arrow-down_normal.svg"
overlay_stretch=FALSE
arrow_direction=DOWN
}
image
{
function=STEPPER
state=NORMAL
file="../theme/images/arrow-bg.svg"
stretch=FALSE
overlay_file="../theme/images/arrow-left_normal.svg"
overlay_stretch=FALSE
arrow_direction=LEFT
}
image
{
function=STEPPER
state=NORMAL
file="../theme/images/arrow-bg.svg"
stretch=FALSE
overlay_file="../theme/images/arrow-right_normal.svg"
overlay_stretch=FALSE
arrow_direction=RIGHT
}
image
{
function=STEPPER
state=ACTIVE
file="../theme/images/arrow-bg.svg"
stretch=FALSE
overlay_file="../theme/images/arrow-up_hover.svg"
overlay_stretch=FALSE
arrow_direction=UP
}
image
{
function=STEPPER
state=ACTIVE
file="../theme/images/arrow-bg.svg"
stretch=FALSE
overlay_file="../theme/images/arrow-down_hover.svg"
overlay_stretch=FALSE
arrow_direction=DOWN
}
image
{
function=STEPPER
state=ACTIVE
file="../theme/images/arrow-bg.svg"
stretch=FALSE
overlay_file="../theme/images/arrow-left_hover.svg"
overlay_stretch=FALSE
arrow_direction=LEFT
}
image
{
function=STEPPER
state=ACTIVE
file="../theme/images/arrow-bg.svg"
stretch=FALSE
overlay_file="../theme/images/arrow-right_hover.svg"
overlay_stretch=FALSE
arrow_direction=RIGHT
}
image
{
function=STEPPER
state=PRELIGHT
file="../theme/images/arrow-bg.svg"
stretch=FALSE
overlay_file="../theme/images/arrow-up_hover.svg"
overlay_stretch=FALSE
arrow_direction=UP
}
image
{
function=STEPPER
state=PRELIGHT
file="../theme/images/arrow-bg.svg"
stretch=FALSE
overlay_file="../theme/images/arrow-down_hover.svg"
overlay_stretch=FALSE
arrow_direction=DOWN
}
image
{
function=STEPPER
state=PRELIGHT
file="../theme/images/arrow-bg.svg"
stretch=FALSE
overlay_file="../theme/images/arrow-left_hover.svg"
overlay_stretch=FALSE
arrow_direction=LEFT
}
image
{
function=STEPPER
state=PRELIGHT
file="../theme/images/arrow-bg.svg"
stretch=FALSE
overlay_file="../theme/images/arrow-right_hover.svg"
overlay_stretch=FALSE
arrow_direction=RIGHT
}
image
{
function=STEPPER
state=INSENSITIVE
file="../theme/images/arrow-bg.svg"
stretch=FALSE
overlay_file="../theme/images/arrow-up_insensitive.svg"
overlay_stretch=FALSE
arrow_direction=UP
}
image
{
function=STEPPER
state=INSENSITIVE
file="../theme/images/arrow-bg.svg"
stretch=FALSE
overlay_file="../theme/images/arrow-down_insensitive.svg"
overlay_stretch=FALSE
arrow_direction=DOWN
}
image
{
function=STEPPER
state=INSENSITIVE
file="../theme/images/arrow-bg.svg"
stretch=FALSE
overlay_file="../theme/images/arrow-left_insensitive.svg"
overlay_stretch=FALSE
arrow_direction=LEFT
}
image
{
function=STEPPER
state=INSENSITIVE
file="../theme/images/arrow-bg.svg"
stretch=FALSE
overlay_file="../theme/images/arrow-right_insensitive.svg"
overlay_stretch=FALSE
arrow_direction=RIGHT
}
}
}
class"GtkScrollbar"style"gtkscrollbar"
