style"alttab"{
fg[NORMAL]="white"
fg[SELECTED]="white"
fg[PRELIGHT]=shade (0.8,@hilight)
fg[ACTIVE]=@hilight
fg[INSENSITIVE]="grey"
bg[NORMAL]="black"
bg[PRELIGHT]="black"
bg[SELECTED]="black"
bg[ACTIVE]="black"
bg[INSENSITIVE]="black"
base[NORMAL]="black"
base[PRELIGHT]="black"
base[ACTIVE]="black"
base[SELECTED]="black"
base[INSENSITIVE]="black"
text[NORMAL]="white"
text[PRELIGHT]="white"
text[ACTIVE]="white"
text[SELECTED]="white"
text[INSENSITIVE]="grey"
font_name="bold"
engine"mist"{}}
widget_class"*Xfwm4TabwinWidget*"style"alttab"

style"alttabicon"{
bg[SELECTED]=@hilight
font_name="bold"
engine"mist"{}}
widget_class"*Xfwm4TabwinWidget*Image*"style"alttabicon"
