style"gtkframe"
{
xthickness=1
ythickness=1
engine"pixmap"
{
image
{
function=SHADOW_GAP
shadow=IN
file="../themedark/images/shadow_in-groupbox.svg"
border={1,1,1,1}
stretch=TRUE
gap_start_file="../themedark/images/shadow_in-groupbox_gap.svg"
gap_end_file="../themedark/images/shadow_in-groupbox_gap.svg"
}
image
{
function=SHADOW_GAP
shadow=ETCHED_IN
file="../themedark/images/shadow_in-groupbox.svg"
border={1,1,1,1}
stretch=TRUE
gap_start_file="../themedark/images/shadow_in-groupbox_gap.svg"
gap_end_file="../themedark/images/shadow_in-groupbox_gap.svg"
}
image
{
function=SHADOW_GAP
shadow=OUT
file="../themedark/images/shadow_out-groupbox.svg"
border={1,1,0,2}
stretch=TRUE
gap_start_file="../themedark/images/shadow_out-groupbox_gap.svg"
gap_end_file="../themedark/images/shadow_out-groupbox_gap.svg"
}
image
{
function=SHADOW_GAP
shadow=ETCHED_OUT
file="../themedark/images/shadow_out-groupbox.svg"
border={1,1,0,2}
stretch=TRUE
gap_start_file="../themedark/images/shadow_out-groupbox_gap.svg"
gap_end_file="../themedark/images/shadow_out-groupbox_gap.svg"
}
image
{
function=SHADOW_GAP
shadow=NONE
file="../theme/images/trans.svg"
stretch=FALSE
gap_start_file="../theme/images/trans.svg"
gap_end_file="../theme/images/trans.svg"
}}}
class"GtkFrame"style"gtkframe"

style"gtkframe2"{
fg[NORMAL]=@windowtext
font_name="bold"}
widget_class"*GtkFrame.GtkLabel"style"gtkframe2"

