style"gtkmenu" = "gtkwidget"{
xthickness=1
ythickness=0
fg[NORMAL]=@windowtext
fg[PRELIGHT]=@hilighttext
fg[SELECTED]=@hilighttext
fg[ACTIVE]=@hilighttext
fg[INSENSITIVE]=@inactivewindowtext
bg[NORMAL]=@basebg
bg[PRELIGHT]=@basebg
bg[SELECTED]=@hilight
bg[ACTIVE]=@basebg
bg[INSENSITIVE]=@basebg
text[NORMAL]=@windowtext
text[PRELIGHT]=@hilighttext
text[ACTIVE]=@hilighttext
text[SELECTED]=@hilighttext
text[INSENSITIVE]=@inactivewindowtext
GtkMenu::reserve-toggle-size=0
GtkMenu::arrow-placement=GTK_ARROWS_BOTH
GtkMenu::double-arrows=0
engine"pixmap"{
image{
function=BOX
detail="menu"
file="../themedark/images/shadow.svg"
stretch=TRUE
border={1,1,1,1}}
image{
function=SHADOW
shadow=OUT
file="../theme/images/trans.svg"
stretch=FALSE}
image
{
function=ARROW
state=INSENSITIVE
file="../themedark/images/arrow-bg.svg"
stretch=FALSE
overlay_file="../themedark/images/arrow-up_insensitive.svg"
overlay_stretch=FALSE
arrow_direction=UP
}
image
{
function=ARROW
state=INSENSITIVE
file="../themedark/images/arrow-bg.svg"
stretch=FALSE
overlay_file="../themedark/images/arrow-down_insensitive.svg"
overlay_stretch=FALSE
arrow_direction=DOWN
}
image
{
function=ARROW
state=NORMAL
file="../themedark/images/arrow-bg.svg"
stretch=FALSE
overlay_file="../themedark/images/arrow-up_normal.svg"
overlay_stretch=FALSE
arrow_direction=UP
}
image
{
function=ARROW
state=NORMAL
file="../themedark/images/arrow-bg.svg"
stretch=FALSE
overlay_file="../themedark/images/arrow-down_normal.svg"
overlay_stretch=FALSE
arrow_direction=DOWN
}
image
{
function=ARROW
state=ACTIVE
file="../themedark/images/arrow-bg.svg"
stretch=FALSE
overlay_file="../themedark/images/arrow-up_hover.svg"
overlay_stretch=FALSE
arrow_direction=UP
}
image
{
function=ARROW
state=ACTIVE
file="../themedark/images/arrow-bg.svg"
stretch=FALSE
overlay_file="../themedark/images/arrow-down_hover.svg"
overlay_stretch=FALSE
arrow_direction=DOWN
}
image
{
function=ARROW
state=PRELIGHT
file="../themedark/images/arrow-bg.svg"
stretch=FALSE
overlay_file="../themedark/images/arrow-up_hover.svg"
overlay_stretch=FALSE
arrow_direction=UP
}
image
{
function=ARROW
state=PRELIGHT
file="../themedark/images/arrow-bg.svg"
stretch=FALSE
overlay_file="../themedark/images/arrow-down_hover.svg"
overlay_stretch=FALSE
arrow_direction=DOWN
}}}
class"GtkMenu"style"gtkmenu"

style"gtkmenuitem"{
xthickness=1
ythickness=6 ##recommend iconsize is 22px
fg[NORMAL]=@windowtext
fg[PRELIGHT]=@hilighttext
fg[SELECTED]=@hilighttext
fg[ACTIVE]=@hilighttext
fg[INSENSITIVE]=@inactivewindowtext
bg[NORMAL]=@basebg
bg[PRELIGHT]=@hilight
bg[SELECTED]=@hilight
bg[ACTIVE]=@basebg
bg[INSENSITIVE]=@basebg
text[NORMAL]=@windowtext
text[PRELIGHT]=@hilighttext
text[ACTIVE]=@hilighttext
text[SELECTED]=@hilighttext
text[INSENSITIVE]=@inactivewindowtext
GtkTearoffMenuItem::shadow-style=GTK_SHADOW_NONE
GtkMenuItem::shadow-style=GTK_SHADOW_NONE
GtkMenuItem::arrow-scaling=0.6
engine"pixmap"{
image{
function=SHADOW
shadow=IN
file="../theme/images/trans.svg"
stretch=FALSE}
image{
function=SHADOW
shadow=ETCHED_IN
file="../theme/images/trans.svg"
stretch=FALSE}
image{
function=SHADOW
shadow=OUT
file="../theme/images/trans.svg"
stretch=FALSE}
image{
function=SHADOW
shadow=ETCHED_OUT
file="../theme/images/trans.svg"
stretch=FALSE}
image{
function=SHADOW
shadow=NONE
file="../theme/images/trans.svg"
stretch=FALSE}
image{
function=ARROW
state=PRELIGHT
file="../themedark/images/arrow-bg.svg"
stretch=FALSE
overlay_file="../themedark/images/arrow-right_active.svg"
overlay_stretch=FALSE
arrow_direction=RIGHT}
image{
function=ARROW
state=INSENSITIVE
file="../themedark/images/arrow-bg.svg"
stretch=FALSE
overlay_file="../themedark/images/arrow-right_insensitive.svg"
overlay_stretch=FALSE
arrow_direction=RIGHT}
image{
function=ARROW
state=NORMAL
file="../themedark/images/arrow-bg.svg"
stretch=FALSE
overlay_file="../themedark/images/arrow-right_normal.svg"
overlay_stretch=FALSE
arrow_direction=RIGHT}
image{
function=ARROW
state=ACTIVE
file="../themedark/images/arrow-bg.svg"
stretch=FALSE
overlay_file="../themedark/images/arrow-right_hover.svg"
overlay_stretch=FALSE
arrow_direction=RIGHT
}}}
widget_class"*GtkMenu*Item*"style"gtkmenuitem"
widget_class"*GtkRecentChooserMenu*"style"gtkmenuitem"
widget_class"*Gtk*Menu*Item*"style"gtkmenuitem"

style"gtkseperatormenuitem"{
xthickness=0
ythickness=0
fg[NORMAL]=@basebg
fg[PRELIGHT]=@basebg
fg[SELECTED]=@basebg
fg[ACTIVE]=@basebg
fg[INSENSITIVE]=@basebg
bg[NORMAL]=@basebg
bg[PRELIGHT]=@basebg
bg[SELECTED]=@basebg
bg[ACTIVE]=@basebg
bg[INSENSITIVE]=@basebg
engine"pixmap"{
image{
function=SHADOW
file="../theme/images/trans.svg"
stretch=FALSE}
image{
function=BOX
detail="hseparator"
file="../themedark/images/color-dbdbdb.svg"
stretch=TRUE}
image{
function=HLINE
detail="hseparator"
file="../themedark/images/color-dbdbdb.svg"
stretch=TRUE}}}
widget"*GtkSeparatorMenuItem*"style"gtkseperatormenuitem"

style"gtktearoffmenuitem"{
xthickness=0
ythickness=1
engine"mist"{}}
widget_class"*GtkTearoffMenuItem*"style"gtktearoffmenuitem"
