style"gtkprogressbar"{
xthickness=0
ythickness=0
GtkProgressBar::min-horizontal-bar-height=7
GtkProgressBar::min-horizontal-bar-width=100
GtkProgressBar::min-vertical-bar-height=100
GtkProgressBar::min-vertical-bar-width=7
GtkProgressBar::xspacing=0
GtkProgressBar::yspacing=0
fg[NORMAL]="#e5e5e5"
fg[PRELIGHT]=@hilight
fg[SELECTED]=@hilight
fg[ACTIVE]=@hilight
fg[INSENSITIVE]=@inactivewindowtext
bg[NORMAL]=@basebg
bg[PRELIGHT]=@hilight
bg[SELECTED]=@hilight
bg[ACTIVE]=@hilight
bg[INSENSITIVE]=@inactivewindowtext
base[NORMAL]=@window
base[PRELIGHT]=@window
base[ACTIVE]=@hilight
base[SELECTED]=@hilight
base[INSENSITIVE]=@window
font_name="bold"
engine"pixmap"
{
image
{
function=SHADOW
file="../theme/images/trans.svg"
stretch=FALSE
}
image
{
function=BOX
detail="trough"
file="../themedark/images/progressbar_trough.svg"
border={3,3,3,3}
stretch=TRUE
}
image
{
function=BOX
detail="bar"
file="../themedark/images/progressbar_progress.svg"
border={3,3,3,3}
stretch=TRUE
}}}
class"GtkProgressBar"style"gtkprogressbar"
