style"gtktoolbarhandle"{
xthickness=1
ythickness=1
bg[NORMAL]=@toolbar
bg[PRELIGHT]=@toolbar
bg[SELECTED]=@toolbar
bg[ACTIVE]=@toolbar
bg[INSENSITIVE]=@toolbar
fg[NORMAL]=@windowtext
fg[PRELIGHT]=@windowtext
fg[SELECTED]=@windowtext
fg[ACTIVE]=@windowtext
fg[INSENSITIVE]=@inactivewindowtext
GtkHandleBox::shadow-type=GTK_SHADOW_NONE
engine"pixmap"{
image{
function=BOX
orientation=VERTICAL
file="../themedark/images/toolbar_vertical.svg"
stretch=TRUE
border={1,1,0,0}}
image{
function=HANDLE
detail="vhandle"
orientation=VERTICAL
file="../themedark/images/toolbar_horizontal.svg"
stretch=TRUE
border={1,1,0,0}
overlay_file="../theme/images/handle_vertical.svg"
overlay_stretch=FALSE}
image{
function=BOX
orientation=HORIZONTAL
file="../themedark/images/toolbar_horizontal.svg"
stretch=TRUE
border={0,0,1,1}}
image{
function=HANDLE
orientation=HORIZONTAL
detail="hhandle"
file="../themedark/images/toolbar_vertical.svg"
stretch=TRUE
border={0,0,1,1}
overlay_file="../theme/images/handle_horizontal.svg"
overlay_stretch=FALSE}
}}
widget"*GtkHandleBox"style"gtktoolbarhandle"
